import platform

SYSTEM = platform.system().lower()

USERS_FOLDER = "repository_views"
LOG_FOLDER = "log"

REPO_VIEWS_DB_FILE_NAME = "views.db"
FILE_VIEWS_DB_FILE_NAME = "file_views.db"

REPO_VIEWS_DB_TABLE_NAME = "REPO_VIEWS"
FILE_VIEWS_DB_TABLE_NAME = "FILE_VIEWS"


REPO_VIEWS_DB_COLUMN_TIMESTAMP = "TIMESTAMP"
REPO_VIEWS_DB_COLUMN_VIEW_COUNTS = "VIEWS"
REPO_VIEWS_DB_COLUMN_UNIQUES = "UNIQUES"
REPO_VIEWS_DB_COLUMNS = (REPO_VIEWS_DB_COLUMN_TIMESTAMP, REPO_VIEWS_DB_COLUMN_VIEW_COUNTS, REPO_VIEWS_DB_COLUMN_UNIQUES)

FILE_VIEWS_DB_COLUMN_START_TIMESTAMP = "START_DATE_TIMESTAMP"
FILE_VIEWS_DB_COLUMN_END_TIMESTAMP = "END_DATE_TIMESTAMP"
FILE_VIEWS_DB_COLUMN_FILE_NAME = "FILE"
FILE_VIEWS_DB_COLUMN_VIEW_COUNTS = "VIEWS"
FILE_VIEWS_DB_COLUMN_UNIQUES = "UNIQUES"
FILE_VIEWS_DB_COLUMNS = (FILE_VIEWS_DB_COLUMN_START_TIMESTAMP, FILE_VIEWS_DB_COLUMN_END_TIMESTAMP, FILE_VIEWS_DB_COLUMN_FILE_NAME, FILE_VIEWS_DB_COLUMN_VIEW_COUNTS, FILE_VIEWS_DB_COLUMN_UNIQUES)

GENERAL_DATE_PATTERN = "%d/%m/%Y %H:%M:%S"
FILE_DATE_PATTERN = "%d.%m.%Y %H.%M.%S"
TABLE_DATE_PATTERN = "%d/%m/%Y"

CLEAR_COMMAND = "cls" if SYSTEM == "windows" else "clear"
